language: node_js
node_js:
  - 'stable'
before_script:
  - npm install -g istanbul
  - npm install coveralls
script:
  - istanbul cover ./node_modules/.bin/grunt --report lcovonly && istanbul report text && ( cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true ) && rm -rf 
